### ISSUE TITLE
Some files download but end up being stored with 0 bytes?

### ISSUE THREAD

**Issue by sevgit** [confraria/fm-download#1]
Title says it all, some lessons get downloaded according to the console but then end up being written as an extensionless 0 byte file. Any ideas?

**Comment by confraria** [comment]
is it consistently reproducible?
Any special characters in the titles or particularly long names?
Also what OS are you using?

**Comment by sevgit** [comment]
So far it looks like it had to do with the lesson titles, every title including a colon/ampersand had this issue. I can take a deeper look into the regex later but so far I've managed to solve this partially by changing the filename output to a hardcoded name (i.e Node Api Course).

I'm using windows 7 here, by the way.

**Comment by confraria** [comment]
added sanitize-filename to filter invalid characters. let me know if it solves it.

**Comment by sevgit** [comment]
So far so good, haven't had this happen again. Grats!
